# -*- coding: utf-8 -*-

from num2words import num2words

from odoo import _, api, fields, models


class PO(models.Model):
    _inherit = ["purchase.order"]

    @api.onchange('partner_id')
    def onchange_partner_style(self):
        self.po_style = self.partner_id.style or self.env.user.company_id.df_style or self.env.ref(
            'z_purchase_custom_report_templates.df_style_for_all_reports').id
        self.rfq_style = self.partner_id.style or self.env.user.company_id.df_style or self.env.ref(
            'z_purchase_custom_report_templates.df_style_for_all_reports').id

    po_style = fields.Many2one('report.template.settings',
                               'PO Style',
                               help="Select Style to use when printing the PO",
                               default=lambda self: self.partner_id.style or
                               self.env.user.company_id.df_style)
    amount_words = fields.Char(
        'Amount in Words:',
        help=
        "The total amount in words is automatically generated by the system..few languages are supported currently",
        compute='_compute_num2words')

    def _compute_num2words(self):
        for rec in self:
            style = rec.po_style or rec.partner_id.style or rec.env.user.company_id.df_style or rec.env.ref(
                'z_purchase_custom_report_templates.df_style_for_all_reports')
            if style and style.aiw_report:
                try:
                    rec.amount_words = (
                        num2words(rec.amount_total, lang=rec.partner_id.lang or
                            'en') +
                        ' ' + (rec.currency_id.currency_name or '')).upper()
                except NotImplementedError:
                    rec.amount_words = (
                        num2words(rec.amount_total, lang='en') + ' ' +
                        (rec.currency_id.currency_name or '')).upper()
            else:
                rec.amount_words = _('Disabled')
