# -*- coding: utf-8 -*-

from num2words import num2words

from odoo import _, api, fields, models


class SO(models.Model):
    _inherit = "sale.order"

    @api.onchange('partner_id')
    def onchange_partner_style(self):
        """ @onchage method to assign style to a document based on chosen partner"""

        self.style = self.partner_id.style or self.env.user.company_id.df_style or\
                self.env.ref('z_sale_custom_report_templates.df_style_for_all_reports').id

    style = fields.Many2one(
        'report.template.settings',
        'Quote/Order Style',
        help="Select Style to use when printing the Sales Order or Quote",
        default=lambda self: self.partner_id.style or self.env.user.company_id.
        df_style)
    project_title = fields.Char(
        'Title',
        help=
        "The title of your customer project or work you are doing for your customer"
    )
    amount_words = fields.Char(
        'Amount in Words:',
        help=
        "The total amount in words is automatically generated by the system",
        compute='_compute_num2words')

    def _compute_num2words(self):
        for rec in self:
            style = rec.style or rec.partner_id.style or \
                    rec.env.user.company_id.df_style or rec.env.ref(
                            'z_sale_custom_report_templates.df_style_for_all_reports')
            if style and style.aiw_report:
                try:
                    rec.amount_words = (
                        num2words(rec.amount_total, lang=rec.partner_id.lang or
                            'en') +
                        ' ' + (rec.currency_id.currency_name or '')).upper()
                except NotImplementedError:
                    rec.amount_words = (
                        num2words(rec.amount_total, lang='en') + ' ' +
                        (rec.currency_id.currency_name or '')).upper()
            else:
                rec.amount_words = _('Disabled')
